{{ if .Values.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
      app: "{{ .Values.App }}"
  ingress:
    - {}
{{ end }}
